name: yuread
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  jwt_decoder: ^2.0.1
  intl: ^0.20.2
  async: ^2.12.0
  material_color_utilities: ^0.11.1
  vector_math: ^2.1.4
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  lints: ^5.0.0
  vm_service: 14.3.1
  fl_chart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
